services:
  web:
    image: authoritative_nameserver:latest
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD:
    depends_on:
      - redis
    restart: always
  redis:
    image: "redis"
    ports:
      - "6379:6379"